name: Selenium IDE CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      
    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Install Chrome
      run: 
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        
    - name: Execute unit tests
      run: dotnet test

    - name: Install dependencies
      run: dotnet restore

    - name: build
      run: dotnet build --no-restore

    - name: run tests
      env:
        CHROMEWEBDRIVER: /usr/bin/google-chrome
      run: dotnet test -- verbosity normal
